# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f4ed9ac340df7cbdcc08de37c3623150f968109a67b9be4a45ca3b721106ab24ae0b6a04a89d03f2e003a0e6a8c98c6e7eddaa91d3466e61705bb6852b4a9162

test:
  secret_key_base: c43524a07ddc68e50d2976a4735fb315172aef9a85585e8310788663729b731312e432fc3209130ddc4b94b3f70573b413dc3ab03a2de5eeac32ef775dcb2c64

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
